import pyfiglet
str='''Your  Timer  Will  Be   Started  Soon.........
Your  All  Files  Will  Be  Deleted  In  10  secs .....
Closing  Terminal  Won't   Help  .......'''

print(pyfiglet.figlet_format(str))